spring:
  redis:
    host: localhost
    port: 6379
    timeout: 6000
    database: 5

wind:
  #数据库配置
  datasource:
    address: 127.0.0.1:3306
    schema: wind-center
    username: root
    password: root
