spring:
  redis:
    host: localhost
    port: 6379
    timeout: 6000
    database: 5
  datasource:
    #  要自动建表需要带上参数 &nullCatalogMeansCurrent=true
    url: jdbc:mysql://127.0.0.1:3306/wind-able?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Hongkong
    username: root
    password: root
